[tool.black]
line-length = 120
target-version = ['py36','py37','py38','py39','py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | __pycache__
  | docs
  | .dockerignore
  | .flake8
  | .gitignore
  | .pre-commit-config.yaml
  | build.sh
  | CHANGELOG.MD
  | Dockerfile
  | latest-version
  | pyproject.toml
)/
'''
